name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup-python ${{ matrix.python }}
      id: setup-python
      uses: ./
      with:
        python-version: ${{ matrix.python }}

    - name: Check python-path
      run: ./__tests__/check-python-path.sh '${{ steps.setup-python.outputs.python-path }}'
      shell: bash

    - name: Validate version
      run: |
        $pythonVersion = (python --version)
        if ("Python ${{ matrix.python }}" -ne "$pythonVersion"){
          Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python }}"
          exit 1
        }
        $pythonVersion
      shell: pwsh

    - name: Run main code
      run: |
        source deepfake_env/bin/activate
        python3 src/main.py
        