name: pylint
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Set up Virtual env
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt

    - name: Set up pip
      uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Install requirements
      run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Analysing the code with pylint
      run: |
        pylint src